// 100 real company stories, ten beats each (the timeline in plan.ts gives each beat its shot).
// Beat shorthand, fields split by "|":
//   Y|year|from|label|sub          N|num|pre|suf|title|sub      T|title|hl|sub        Q|quote|hl|who
//   M|who|msg;msg;msg|hl  (chat)   C|title|A|a|B|b              L|title|item;item     P|title|sub|item;item  (shows the prop)
//   H|WORD|sub|num|from  (the twist on the music drop; H- / H+ force the tone)      E|closing line|hl|search question
import type { Beat } from './core';

type Raw = [co: string, c1: string, c2: string, prop: string, tone: 'up' | 'down', beats: string[]];
const R: Raw[] = [
  ['Kodak', '#FFB700', '#E30613', 'camera', 'down', ['Y|1975|1900|Kodak|Rochester, Nueva York', 'N|90||%|Kodak era intocable|del rollo vendido en EE.UU.', 'P|Inventó algo que cambiaría el mundo|La cámara digital|3.6 kg;23 s por foto;0.01 MP',
    'H|QUIEBRA|y eso la llevó a la…|2012|1975', 'T|Steve Sasson tenía 24 años|24 años|Ingeniero de Kodak', 'Q|Está lindo… pero no se lo digas a nadie.|no se lo digas a nadie|La junta de Kodak, según Sasson',
    'T|Y siguieron vendiendo rollo|rollo|mientras el mundo se volvía digital', 'C|2012|Kodak|Quiebra en enero|Instagram|Vendida por $1,000 M en abril', 'N|131||años|De historia|1881 – 2012', 'E|La inventó. Y la escondió.|la escondió.|¿por qué quebró kodak?']],
  ['Blockbuster', '#0046AD', '#FFD200', 'vhs', 'down', ['Y|2000|1985|Blockbuster|Dallas, Texas', 'N|9000||tiendas|Blockbuster llegó a tener|en su mejor momento', 'M|Junta de Blockbuster|Netflix se vende por $50 M.;¿Películas por correo?;No, gracias.|No, gracias.',
    'H|NO|a comprar Netflix por $50 M||', 'T|Se rieron de Netflix en la junta|se rieron|según el cofundador de Netflix', 'Y|2007|2000|Netflix|lanza el streaming', 'Y|2010|2007|Blockbuster|se declara en quiebra',
    'N|1||tienda|Hoy queda|en Bend, Oregon', 'C|Hoy|Blockbuster|1 tienda|Netflix|Más de 300 M de cuentas', 'E|Se rieron del futuro.|del futuro.|¿quién se rió de netflix?']],
  ['Nokia', '#124191', '#00A3E0', 'phone', 'down', ['Y|2007|1990|Nokia|Espoo, Finlandia', 'N|40||%|Casi el|de los celulares del mundo eran Nokia', 'T|Ese año llegó el iPhone|iPhone|Pantalla táctil. Sin teclado.',
    'H|TARDE|Nokia reaccionó…||', 'L|Nokia siguió apostando por|Teclados físicos;Symbian;Celulares baratos', 'T|Fue la marca #1 de celulares 14 años seguidos|14 años|', 'Y|2013|2007|Nokia|vende sus celulares a Microsoft',
    'N|5.4|€|mil M|Por|', 'T|Empezó en 1865 como fábrica de papel|fábrica de papel|y luego hizo botas de hule', 'E|Ser el #1 no te salva.|no te salva.|¿qué pasó con nokia?']],
  ['BlackBerry', '#1A1A1A', '#2E7BFF', 'qwerty', 'down', ['Y|2009|1999|BlackBerry|Waterloo, Canadá', 'T|El celular de presidentes y CEOs|presidentes|Obama no quiso soltar el suyo', 'L|Su fórmula ganadora|Teclado físico;Correo seguro;Batería de días',
    'H|0%|del mercado en 2017|0|50', 'T|Pensaron que nadie querría escribir en vidrio|en vidrio|', 'Y|2016|2009|BlackBerry|deja de fabricar celulares', 'C|2007|BlackBerry|Teclado|iPhone|Pantalla',
    'T|Hoy vende software de seguridad|software|', 'T|Del bolsillo de todos al olvido|al olvido|', 'E|Lo que te hizo ganar puede hacerte perder.|perder.|¿qué pasó con blackberry?']],
  ['Toys"R"Us', '#0057B8', '#F7A600', 'brick', 'down', ['Y|2000|1948|Toys"R"Us|Wayne, Nueva Jersey', 'T|Le entregó su tienda online a Amazon|a Amazon|Un contrato de 10 años', 'N|50|$| M|Amazon cobraba|al año, más un % de ventas',
    'H|DEMANDA|Toys"R"Us vs. Amazon|2004|2000', 'T|Cuando volvió a vender online, ya era tarde|ya era tarde|', 'Y|2017|2004|Toys"R"Us|se declara en quiebra', 'Y|2018|2017|Toys"R"Us|cierra sus tiendas en EE.UU.',
    'T|Le enseñó a su rival a vender juguetes|a su rival|', 'C|Quién ganó|Toys"R"Us|Quiebra|Amazon|Tus clientes', 'E|Nunca terceriza tu futuro.|tu futuro.|¿por qué quebró toys r us?']],
  ['Xerox', '#E2231A', '#0072CE', 'mouse', 'down', ['Y|1973|1960|Xerox PARC|Palo Alto, California', 'L|Inventaron en su laboratorio|Interfaz gráfica;Ventanas e íconos;Impresora láser', 'T|Xerox solo quería vender fotocopiadoras|fotocopiadoras|',
    'H|1979|Steve Jobs visita el laboratorio|1979|1970', 'T|Vio la interfaz gráfica y entendió todo|entendió todo|', 'Y|1984|1979|Apple|lanza la Macintosh', 'T|Xerox inventó la computadora moderna|inventó|y la dejó ir',
    'Q|No tenían idea de lo que una computadora podía hacer.|No tenían idea|Steve Jobs sobre Xerox (parafraseado)', 'C|Quién se quedó con el futuro|Xerox|Fotocopias|Apple y Microsoft|La computadora personal', 'E|Inventar no basta. Hay que apostar.|apostar.|¿quién inventó la interfaz gráfica?']],
  ['MySpace', '#003399', '#5B9BD5', 'laptop', 'down', ['Y|2005|2003|MySpace|la red social #1', 'N|580|$| M|News Corp la compra por|', 'T|En 2006 fue el sitio más visitado de EE.UU.|más visitado|',
    'H|FACEBOOK|llegó con perfiles limpios||', 'L|MySpace se llenó de|Anuncios;Perfiles lentos;Spam', 'Y|2011|2005|MySpace|se vende por $35 M', 'N|35|$| M|De $580 M a|en 6 años',
    'T|Tu primer amigo era Tom|Tom|Tom Anderson, cofundador', 'C|2005 → 2011|Compra|$580 M|Venta|$35 M', 'E|La comunidad se va en un clic.|un clic.|¿qué pasó con myspace?']],
  ['Yahoo', '#6001D2', '#FF0080', 'search', 'down', ['Y|1998|1994|Yahoo|Sunnyvale, California', 'N|1|$| M|Google se ofreció por|y Yahoo dijo que no', 'T|2002: otra oportunidad|otra oportunidad|Google pedía $5,000 M. Yahoo dijo que no.',
    'H|NO|a $44,600 M de Microsoft (2008)||', 'N|44.6|$| mil M|Microsoft ofreció|en 2008', 'Y|2016|2008|Yahoo|acepta venderse a Verizon', 'N|4.48|$| mil M|Por solo|10 veces menos',
    'T|Pudo comprar Google por un millón|un millón|', 'C|Lo que valen|Yahoo|$4,480 M|Google|Más de $1 billón', 'E|El orgullo cuesta miles de millones.|miles de millones.|¿yahoo pudo comprar google?']],
  ['Sears', '#004B8D', '#00A3E0', 'box', 'down', ['Y|1888|1880|Sears|Catálogo por correo', 'T|Vendía de todo por catálogo|de todo|hasta casas para armar', 'N|70000||casas|Vendió más de|en kit, por correo',
    'H|AMAZON|hizo lo mismo… en internet||', 'T|Sears tenía el Amazon antes que Amazon|antes que Amazon|', 'T|Pero no llevó su catálogo a internet a tiempo|a tiempo|', 'Y|2018|1888|Sears|se declara en quiebra',
    'L|Sears tuvo primero|El catálogo;La logística;Los clientes', 'C|Mismo modelo|Sears|Catálogo en papel|Amazon|Catálogo en internet', 'E|Tener la idea no basta. Hay que moverla.|moverla.|¿por qué quebró sears?']],
  ['Polaroid', '#F7B500', '#0096D6', 'polaroid', 'down', ['Y|1948|1937|Polaroid|primera cámara instantánea', 'T|La foto salía en segundos|en segundos|Magia en 1948', 'T|Ganaba con la película, no con la cámara|la película|',
    'H|QUIEBRA|Polaroid|2001|1948', 'T|Lo digital hizo innecesaria la película|innecesaria|', 'Y|2008|2001|Polaroid|deja de fabricar película', 'T|Unos fans compraron la última fábrica|la última fábrica|The Impossible Project, 2008',
    'T|Hoy lo instantáneo volvió como nostalgia|nostalgia|', 'C|Su negocio|Antes|Película|Después|Nostalgia', 'E|La nostalgia no paga la renta.|la renta.|¿qué pasó con polaroid?']],
  ['Atari', '#E4202E', '#F7941D', 'controller', 'down', ['Y|1982|1972|Atari|E.T. para Atari 2600', 'N|5||semanas|El juego se hizo en|para llegar a Navidad', 'T|Fabricaron millones de cartuchos|millones|',
    'H|ENTERRADOS|en el desierto de Nuevo México|1983|1982', 'T|Nadie lo entendía. Nadie lo jugaba.|Nadie|', 'Y|1983|1982|Videojuegos|la industria colapsa en EE.UU.', 'T|En 2014 los desenterraron|desenterraron|Alamogordo, Nuevo México',
    'L|Lo que salió mal|Prisa;Juego confuso;Demasiado inventario', 'T|Para muchos, el peor juego de la historia|peor juego|', 'E|La prisa sale cara.|cara.|¿por qué enterraron e.t.?']],
  ['Vine', '#00BF8F', '#00A478', 'smartphone', 'down', ['N|6||s|Videos de|en loop', 'Y|2012|2012|Twitter|compra Vine antes de lanzarla', 'T|Inventó el video corto en loop|video corto|',
    'H|CERRADO|Twitter apaga Vine|2016|2012', 'T|Sus creadores pidieron dinero. No se los dieron.|dinero|', 'T|Se fueron a YouTube e Instagram|YouTube|', 'Y|2016|2012|Vine|se apaga',
    'T|Dos años después, TikTok conquistó el mundo|TikTok|', 'C|El mismo formato|Vine|Cerrado|TikTok|Más de mil millones de usuarios', 'E|Si no cuidas a tus creadores, se van.|se van.|¿qué pasó con vine?']],
  ['Quibi', '#8B5CF6', '#22D3EE', 'smartphone', 'down', ['N|1.75|$| mil M|Quibi recaudó|antes de lanzar', 'T|Series de 10 minutos para el celular|10 minutos|', 'T|La fundó un exjefe de Disney|exjefe de Disney|Jeffrey Katzenberg',
    'H|6 MESES|es lo que duró Quibi||', 'T|Lanzó en plena pandemia|pandemia|Abril de 2020', 'T|Nadie estaba en la calle viendo el celular|en la calle|', 'T|No dejaba tomar capturas para compartir|compartir|',
    'Y|2020|2020|Quibi|cierra en diciembre', 'C|El problema|Quibi|Contenido carísimo|TikTok|Contenido de usuarios', 'E|El dinero no compra el momento.|el momento.|¿qué fue quibi?']],
  ['Friendster', '#2E3192', '#F7941D', 'laptop', 'down', ['Y|2002|2002|Friendster|la primera gran red social', 'N|30|$| M|Google ofreció|en acciones', 'T|Esas acciones hoy valdrían miles de millones|miles de millones|',
    'H|NO|Friendster rechaza a Google||', 'T|Sus páginas tardaban muchísimo en cargar|tardaban|', 'T|Los usuarios se fueron a MySpace y Facebook|se fueron|', 'Y|2011|2003|Friendster|se vuelve sitio de juegos',
    'Y|2015|2011|Friendster|cierra', 'T|Llegar primero no es ganar|primero|', 'E|Lento = muerto.|muerto.|¿qué fue friendster?']],
  ['Borders', '#C8102E', '#1D1D1F', 'book', 'down', ['Y|2001|1971|Borders|librerías gigantes', 'T|Le dejó su tienda online a Amazon|a Amazon|igual que Toys"R"Us', 'T|Apostó por CDs y DVDs en sus tiendas|CDs y DVDs|',
    'H|QUIEBRA|Borders|2011|2001', 'T|El Kindle llegó en 2007|Kindle|', 'T|Borders llegó tarde al libro electrónico|tarde|', 'Y|2011|2007|Borders|cierra todas sus tiendas',
    'T|Amazon aprendió de sus clientes|aprendió|gracias a Borders', 'C|Qué vendían|Borders|Metros cuadrados|Amazon|Comodidad', 'E|Tu canal digital es tu negocio.|tu negocio.|¿qué pasó con borders?']],
  ['Motorola', '#5C88DA', '#B8C4D6', 'flip', 'down', ['Y|2004|1928|Motorola|lanza el RAZR', 'N|130||M|El RAZR vendió más de|unidades', 'T|El celular más delgado y deseado|más delgado|',
    'H|LO MISMO|Motorola repitió la fórmula||', 'T|Mientras, el iPhone cambió las reglas|cambió las reglas|', 'Y|2011|2004|Motorola|se divide en dos', 'N|12.5|$| mil M|Google la compra por|en 2012',
    'N|2.9|$| mil M|Y la vende a Lenovo por|en 2014', 'C|2012 → 2014|Google pagó|$12,500 M|Lenovo pagó|$2,900 M', 'E|Un éxito no es un plan.|un plan.|¿qué pasó con el razr?']],
  ['WeWork', '#2B2B2B', '#FFC52F', 'building', 'down', ['N|47|$| mil M|WeWork llegó a valer|en 2019', 'T|Rentaba oficinas… y decía ser tecnológica|tecnológica|', 'L|Lo que vendía|Oficinas compartidas;Cerveza gratis;"Comunidad"',
    'H|CANCELADA|su salida a bolsa (2019)||', 'T|Los documentos revelaron sus pérdidas|pérdidas|', 'T|Su fundador dejó el cargo|dejó el cargo|Adam Neumann, 2019', 'Y|2023|2019|WeWork|se declara en quiebra',
    'C|Lo que decía vs. lo que era|Decía|Empresa tecnológica|Era|Inmobiliaria', 'T|Cara bonita, números feos|números feos|', 'E|Los números no mienten.|no mienten.|¿qué pasó con wework?']],
  ['Theranos', '#3B82F6', '#E74C3C', 'drop', 'down', ['N|9|$| mil M|Theranos llegó a valer|', 'T|Prometía cientos de análisis con una gota de sangre|una gota|', 'T|Elizabeth Holmes dejó Stanford a los 19|19|',
    'H|FRAUDE|las máquinas no funcionaban||', 'T|Usaban equipos de otras marcas a escondidas|a escondidas|', 'Y|2015|2003|Un periódico|publica la investigación', 'Y|2018|2015|Theranos|se disuelve',
    'Y|2022|2018|Holmes|declarada culpable de fraude', 'C|Lo que vendía|Promesa|Una gota|Realidad|Nada', 'E|Sin producto, no hay historia.|no hay historia.|¿qué fue theranos?']],
  ['FTX', '#02A6C2', '#5FCADE', 'coin', 'down', ['N|32|$| mil M|FTX valía|a inicios de 2022', 'T|Comerciales en el Super Bowl|Super Bowl|', 'T|Un estadio con su nombre en Miami|Miami|',
    'H|COLAPSO|noviembre de 2022||', 'T|Usaban el dinero de sus clientes|de sus clientes|', 'Y|2022|2019|FTX|se declara en quiebra', 'N|25||años|Su fundador, condenado a|de prisión',
    'C|Lo que mostraba|Imagen|Genio filántropo|Realidad|Fraude', 'T|La confianza tarda años en construirse|años|', 'E|Y se pierde en días.|en días.|¿qué pasó con ftx?']],
  ['Netflix', '#E50914', '#B20710', 'dvd', 'up', ['N|40|$| USD|Una multa de|por regresar tarde Apollo 13', 'T|Reed Hastings pensó: ¿y sin multas?|sin multas|', 'P|Netflix, 1998|Películas por correo|DVD;Sobre rojo;Sin tiendas',
    'H|STREAMING|Netflix se canibaliza|2007|1998', 'T|Mató su propio negocio antes que otros|su propio negocio|', 'Y|2013|2007|Netflix|estrena House of Cards', 'T|De rentar películas a producirlas|producirlas|',
    'C|2000 vs. hoy|Blockbuster|1 tienda|Netflix|Más de 300 M de cuentas', 'T|El sobre rojo ya no existe|ya no existe|DVD.com cerró en 2023', 'E|Destrúyete antes de que otro lo haga.|antes|¿cómo empezó netflix?']],
  ['Instagram', '#E1306C', '#F77737', 'smartphone', 'up', ['T|Primero se llamaba Burbn|Burbn|una app de check-ins', 'T|Nadie la usaba… excepto para fotos|para fotos|', 'L|Quitaron todo menos|Fotos;Filtros;Likes',
    'H|1 MILLÓN|de usuarios en 2 meses||', 'N|13||empleados|Instagram tenía|', 'N|1000|$| M|Facebook paga|abril de 2012', 'T|Ese mismo año quebró Kodak|quebró Kodak|',
    'T|Hoy tiene más de 2,000 millones de usuarios|2,000 millones|', 'C|Burbn vs. Instagram|Burbn|Hacía de todo|Instagram|Hacía una cosa', 'E|Haz una cosa. Hazla increíble.|increíble.|¿cómo empezó instagram?']],
  ['YouTube', '#FF0000', '#282828', 'play', 'up', ['T|Empezó como sitio de citas|de citas|', 'T|Nadie subió videos de citas|Nadie|', 'T|Así que aceptaron cualquier video|cualquier video|',
    'H|19 SEGUNDOS|"Me at the zoo", el primer video||', 'Y|2006|2005|Google|compra YouTube', 'N|1.65|$| mil M|Google pagó|', 'T|No tenía ni dos años de vida|dos años|',
    'T|Hoy se suben más de 500 horas por minuto|500 horas|', 'C|El plan vs. lo que funcionó|Plan|Citas en video|Realidad|Videos de todo', 'E|Escucha lo que tus usuarios hacen.|hacen.|¿cómo empezó youtube?']],
  ['Slack', '#4A154B', '#36C5F0', 'chat', 'up', ['T|Querían hacer un videojuego|videojuego|Se llamaba Glitch', 'T|El juego fracasó|fracasó|2012', 'T|Pero su chat interno era genial|chat interno|',
    'H|PIVOTE|del juego al chat||', 'Y|2014|2013|Slack|se lanza al público', 'T|Creció más rápido que casi cualquier software de oficina|más rápido|', 'Y|2021|2014|Salesforce|compra Slack',
    'N|27.7|$| mil M|Salesforce pagó|', 'T|Todo salió de un juego que nadie jugó|nadie jugó|', 'E|A veces tu producto es la herramienta.|la herramienta.|¿cómo nació slack?']],
  ['Nintendo', '#E60012', '#0AB9E6', 'cards', 'up', ['Y|1889|1880|Nintendo|Kioto, Japón', 'P|Nintendo vendía|Cartas hanafuda|Cartas;Papel;Kioto', 'L|Luego intentó|Taxis;Hoteles por hora;Arroz instantáneo',
    'H|VIDEOJUEGOS|la apuesta que lo cambió todo||', 'T|Un ingeniero de mantenimiento cambió su destino|ingeniero de mantenimiento|Gunpei Yokoi', 'Y|1985|1889|NES|llega a EE.UU.', 'T|Super Mario revivió a toda una industria|toda una industria|tras el colapso de 1983',
    'T|Más de 135 años después, sigue en pie|135 años|', 'C|1889 vs. hoy|Antes|Cartas de papel|Hoy|Mario, Zelda, Switch', 'E|Cambia el producto. No el propósito.|el propósito.|¿cómo empezó nintendo?']],
  ['Samsung', '#1428A0', '#00B4FF', 'store', 'up', ['Y|1938|1900|Samsung|Daegu, Corea', 'T|Vendía pescado seco y fideos|pescado seco|', 'T|"Samsung" significa "tres estrellas"|tres estrellas|',
    'H|ELECTRÓNICA|1969||', 'Q|Cambien todo, excepto a su esposa y sus hijos.|Cambien todo|Lee Kun-hee, 1993', 'T|Quemó 150,000 teléfonos defectuosos frente a sus empleados|150,000|1995', 'Y|2012|1938|Samsung|ya vende más celulares que Nokia',
    'T|Del pescado seco a los chips|chips|', 'C|1938 vs. hoy|Antes|Pescado seco|Hoy|Chips y celulares', 'E|Ninguna empresa nace siendo lo que será.|lo que será.|¿cómo empezó samsung?']],
  ['Lamborghini', '#DDB321', '#111111', 'tractor', 'up', ['P|Ferruccio Lamborghini fabricaba|Tractores|Tractores;Italia;1948', 'T|Compró un Ferrari y el embrague le fallaba|el embrague|', 'T|Fue a quejarse con Enzo Ferrari|Enzo Ferrari|',
    'H|DESPRECIO|Enzo lo mandó a sus tractores (dice la leyenda)||', 'T|Así que hizo su propio auto|su propio auto|', 'Y|1963|1948|Automobili Lamborghini|nace', 'Y|1966|1963|Miura|el superauto que asustó a todos',
    'T|Hoy compiten de tú a tú|de tú a tú|', 'C|El origen|Ferrari|Carreras|Lamborghini|Una ofensa', 'E|Un "no" puede fundar una marca.|fundar una marca.|¿por qué lamborghini hace autos?']],
  ['Toyota', '#EB0A1E', '#58595B', 'car', 'up', ['P|Toyota empezó con|Telares|Telares automáticos;Sakichi Toyoda;Japón', 'T|Su telar se detenía solo si un hilo se rompía|se detenía solo|', 'T|Vendieron la patente a una empresa inglesa|la patente|',
    'H|AUTOS|con ese dinero||', 'Y|1937|1929|Toyota Motor|nace', 'T|Su sistema de producción cambió las fábricas del mundo|fábricas del mundo|', 'T|Justo a tiempo. Cero desperdicio.|Cero desperdicio.|',
    'Y|2008|1937|Toyota|supera a GM en ventas', 'C|Del hilo al motor|Antes|Telares|Hoy|Autos', 'E|Lo que aprendes en un negocio sirve en el siguiente.|el siguiente.|¿cómo empezó toyota?']],
  ['Play-Doh', '#F6A800', '#E4002B', 'jar', 'up', ['P|Play-Doh era|Limpiador de papel tapiz|Limpiador;Carbón;Paredes', 'T|Las casas dejaron de calentarse con carbón|carbón|', 'T|El producto ya no servía|ya no servía|',
    'H|PLASTILINA|para escuelas||', 'T|Una maestra lo usaba para manualidades|maestra|', 'Y|1956|1950|Play-Doh|se vende como juguete', 'N|3000||M|Se han vendido más de|latas',
    'T|Mismo producto. Otro cliente.|Otro cliente.|', 'C|Antes y después|Antes|Limpiar paredes|Después|Jugar', 'E|A veces el mercado está en otro lado.|otro lado.|¿qué era play-doh?']],
  ['Coca-Cola', '#F40009', '#8B0000', 'bottle', 'up', ['Y|1886|1850|Coca-Cola|Atlanta, Georgia', 'T|La inventó un farmacéutico|farmacéutico|John Pemberton', 'N|9||al día|El primer año vendía|bebidas',
    'H|$2,300|pagó Asa Candler por la fórmula||', 'T|Candler la convirtió en marca|marca|', 'Y|1915|1886|La botella|con curvas, reconocible a oscuras', 'N|2000||M|Hoy se sirven casi|bebidas al día',
    'T|El inventor murió sin verla triunfar|sin verla triunfar|', 'C|Inventar vs. vender|Pemberton|La inventó|Candler|La hizo famosa', 'E|El que vende es el que gana.|vende|¿quién inventó la coca-cola?']],
  ['Airbnb', '#FF5A5F', '#00A699', 'house', 'up', ['Y|2007|2007|Airbnb|San Francisco', 'T|No podían pagar la renta|la renta|', 'P|Rentaron|3 colchones inflables|Colchón;Desayuno;Sala',
    'H|CEREAL|para sobrevivir (2008)||', "L|Vendieron cereal de campaña|Obama O's;Cap'n McCain's", 'N|30000|$| USD|Ganaron unos|con el cereal', 'T|Y por eso los aceptó Y Combinator|por eso|',
    'Y|2020|2008|Airbnb|sale a bolsa', 'C|De colchones a…|2007|3 colchones|Hoy|Millones de anuncios', 'E|Si nadie te invierte, véndele cereal.|cereal.|¿cómo empezó airbnb?']],
  ['Uber', '#06C167', '#276EF1', 'car', 'up', ['Y|2008|2008|París|una noche de nieve', 'T|No conseguían taxi|taxi|', 'T|¿Y si lo pides con un botón?|un botón|',
    'H|UN TOQUE|y llega tu auto||', 'Y|2010|2008|UberCab|San Francisco', 'T|Los taxistas protestaron en todo el mundo|protestaron|', 'L|Cambió la idea de|Taxi;Comida a domicilio;Trabajo',
    'T|Hoy está en más de 70 países|70 países|', 'C|Antes y ahora|Antes|Esperar en la esquina|Ahora|Ver el auto en el mapa', 'E|El problema que te enoja puede ser tu negocio.|tu negocio.|¿cómo nació uber?']],
  ['Amazon', '#FF9900', '#146EB4', 'box', 'up', ['Y|1994|1990|Amazon|un garage en Bellevue', 'T|Solo vendía libros|libros|', 'T|Primero se iba a llamar Cadabra|Cadabra|',
    'H|DE TODO|de libros a todo||', 'T|Perdió dinero durante años para crecer|años|', 'Y|2006|1994|AWS|renta sus servidores al mundo', 'T|Hoy AWS es su negocio más rentable|más rentable|',
    'T|Su primer escritorio: una puerta con patas|una puerta|', 'C|1995 vs. hoy|Antes|Libros|Hoy|Nube, envíos, video', 'E|Empieza chico. Piensa enorme.|enorme.|¿cómo empezó amazon?']],
  ['Apple', '#A2AAAD', '#0071E3', 'computer', 'down', ['Y|1976|1970|Apple|un garage en Los Altos', 'T|Eran tres socios|tres|Jobs, Wozniak y Ronald Wayne', 'N|10||%|Wayne tenía el|de Apple',
    'H|$800|Wayne vende su parte||', 'T|Solo 12 días después de fundarla|12 días|', 'T|Tenía miedo a las deudas|miedo|', 'T|Ese 10% hoy valdría cientos de miles de millones|cientos de miles de millones|',
    'Q|No me arrepiento.|arrepiento|Ronald Wayne, en entrevistas', 'C|La decisión|Vender|$800|Quedarse|Una fortuna', 'E|Las decisiones con miedo salen caras.|caras.|¿quién fue el tercer fundador de apple?']],
  ['Apple', '#A2AAAD', '#0071E3', 'computer', 'up', ['Y|1997|1976|Apple|a semanas de quebrar', 'T|Steve Jobs vuelve a la empresa que lo despidió|lo despidió|', 'N|150|$| M|Microsoft invierte|en Apple',
    'H|4 PRODUCTOS|Jobs elimina todo lo demás||', 'L|Se quedaron con|Escritorio;Portátil;Profesional;Consumidor', 'Y|1998|1997|iMac|de colores', 'Y|2001|1998|iPod|1,000 canciones en tu bolsillo',
    'Y|2007|2001|iPhone|cambia todo', 'T|De casi quebrar a la empresa más valiosa|más valiosa|', 'E|Enfocarse es decir que no.|que no.|¿cómo se salvó apple?']],
  ['Microsoft', '#00A4EF', '#7FBA00', 'floppy', 'up', ['Y|1980|1975|IBM|busca un sistema operativo', 'T|Microsoft no tenía uno|no tenía|', 'T|Así que le compró uno a otra empresa|compró|QDOS, de Seattle Computer Products',
    'H|LICENCIA|Gates no lo vendió: lo licenció||', 'T|IBM pagaba por usarlo, no por quedárselo|no por quedárselo|', 'T|Microsoft podía venderlo a otros fabricantes|a otros|', 'L|Todos los clones de IBM usaron|MS-DOS',
    'Y|1985|1980|Windows 1.0|sale a la venta', 'C|El trato|IBM|Hardware|Microsoft|El software de todos', 'E|Lee la letra pequeña. Mejor: escríbela tú.|escríbela tú.|¿cómo se hizo rico bill gates?']],
  ['Excite', '#FF6A00', '#4285F4', 'search', 'down', ['Y|1999|1996|Google|antes se llamaba BackRub', 'N|750000|$| USD|Google se ofreció a Excite por|', 'T|A Excite le pareció demasiado caro|demasiado caro|',
    'H|NO|Excite rechaza a Google||', 'T|Excite valía millones. Google era un proyecto de estudiantes.|estudiantes|', 'Y|2001|1999|Excite@Home|en quiebra', 'T|Google se volvió el verbo para buscar|el verbo|',
    'C|Lo que valieron|Excite|Quiebra|Google|Más de $1 billón', 'T|Un "no" de $750,000|$750,000|', 'E|Lo barato a veces es lo más caro.|lo más caro.|¿google estuvo en venta?']],
  ['Facebook', '#1877F2', '#42B72A', 'smartphone', 'up', ['Y|2006|2004|Facebook|2 años de vida', 'N|1|$| mil M|Yahoo ofrece|por Facebook', 'T|Zuckerberg tenía 22 años|22 años|',
    'H|NO|Zuckerberg rechaza a Yahoo||', 'T|Su equipo pensó que estaba loco|loco|', 'Y|2012|2006|Facebook|sale a bolsa', 'N|104|$| mil M|Valuada en|',
    'T|Yahoo terminó vendiéndose por $4,480 M|$4,480 M|', 'C|Quién tenía razón|Yahoo ofrecía|$1,000 M|Facebook valió|$104,000 M', 'E|Si crees, no vendas.|no vendas.|¿yahoo quiso comprar facebook?']],
  ['Snapchat', '#FFFC00', '#111111', 'smartphone', 'up', ['Y|2013|2011|Snapchat|tenía 2 años', 'N|3|$| mil M|Facebook ofreció|en efectivo', 'T|Evan Spiegel tenía 23 años|23 años|',
    'H|NO|Snapchat rechaza a Facebook||', 'T|Facebook copió sus Historias|Historias|Instagram Stories, 2016', 'Y|2017|2013|Snap|sale a bolsa', 'N|24|$| mil M|Valuada en|',
    'T|Pero Instagram Stories la superó en usuarios|la superó|', 'C|Lo que pasó|Snapchat|Inventó las Historias|Instagram|Las popularizó', 'E|Si te copian, corre más rápido.|más rápido.|¿snapchat rechazó a facebook?']],
  ['Starbucks', '#00704A', '#D4E9E2', 'coffee', 'up', ['Y|1983|1971|Howard Schultz|viaja a Milán', 'T|Starbucks solo vendía granos de café|granos|', 'T|En Milán vio bares de espresso en cada esquina|cada esquina|',
    'H|TERCER LUGAR|ni casa ni trabajo||', 'T|Los dueños no quisieron… así que él compró Starbucks|compró|1987', 'N|7100||tiendas|En 2008 cerró|por 3 horas', 'T|Para volver a enseñar a hacer espresso|enseñar|',
    'N|40000||tiendas|Hoy tiene más de|', 'C|Lo que vende|Crees que|Café|En realidad|La experiencia', 'E|No vendes lo que vendes.|lo que vendes.|¿cómo creció starbucks?']],
  ['Nike', '#FA5400', '#111111', 'sneaker', 'up', ['Y|1964|1960|Blue Ribbon Sports|el primer nombre de Nike', 'T|Phil Knight vendía tenis desde su auto|su auto|', 'T|Importaba tenis japoneses|japoneses|',
    'H|WAFLERA|ahí nació su suela||', 'N|35|$| USD|El logo costó|1971', 'Y|1971|1964|Nike|nace la marca', 'Y|1985|1971|Air Jordan|sale a la venta',
    'N|126|$| M|Air Jordan vendió en su primer año|', 'C|El inicio|1964|Cajuela de un auto|Hoy|Marca global', 'E|Empieza con lo que tienes.|lo que tienes.|¿cómo empezó nike?']],
  ['Adidas y Puma', '#0F7BFF', '#E4002B', 'sneaker', 'down', ['Y|1924|1900|Hermanos Dassler|Herzogenaurach, Alemania', 'T|Dos hermanos hacían tenis juntos|juntos|', 'T|Jesse Owens ganó con sus tenis en 1936|1936|',
    'H|SEPARADOS|1948||', 'C|Los hermanos|Adolf|Adidas|Rudolf|Puma', 'T|El río dividió el pueblo en dos|el río|', 'T|Había bares, panaderías y escuelas de cada bando|cada bando|',
    'T|Le decían "el pueblo de los cuellos doblados"|cuellos doblados|', 'T|En 2009 jugaron un partido de la paz|de la paz|', 'E|Una pelea familiar creó dos gigantes.|dos gigantes.|¿adidas y puma son hermanos?']],
  ['IKEA', '#0058A3', '#FFDB00', 'box', 'up', ['N|17||años|Ingvar Kamprad fundó IKEA a los|1943', 'T|Vendía lápices y semillas por correo|lápices|', 'T|Un empleado le quitó las patas a una mesa para meterla al auto|le quitó las patas|',
    'H|CAJA PLANA|nace el mueble para armar||', 'T|Tú lo armas. Ellos ahorran. Tú pagas menos.|Tú lo armas.|', 'L|IKEA ahorra en|Envío;Bodega;Armado', 'T|IKEA = Ingvar Kamprad, Elmtaryd, Agunnaryd|Elmtaryd|',
    'T|Hoy está en más de 60 países|60 países|', 'C|La idea|Antes|Muebles armados|IKEA|Muebles en caja plana', 'E|Un problema de logística se volvió el producto.|el producto.|¿cómo empezó ikea?']],
  ['LEGO', '#E3000B', '#FFD500', 'brick', 'up', ['Y|1932|1916|LEGO|Billund, Dinamarca', 'T|Hacía juguetes de madera|de madera|', 'T|"Leg godt" significa "juega bien"|juega bien|',
    'H-|CASI QUIEBRA|2003||', 'T|Se diversificó demasiado|demasiado|parques, ropa, videojuegos', 'T|Volvió a lo básico: el bloque|el bloque|', 'Y|2014|2004|The LEGO Movie|llega a los cines',
    'T|Hoy es la juguetera más grande del mundo|más grande|', 'C|La lección|2003|Hacer de todo|Hoy|Hacer bloques', 'E|Regresa a lo que te hizo grande.|lo que te hizo grande.|¿cómo se salvó lego?']],
  ["McDonald's", '#FFC72C', '#DA291C', 'burger', 'up', ['Y|1954|1940|Ray Kroc|vendedor de batidoras', 'T|Una hamburguesería le pidió 8 batidoras|8 batidoras|', 'T|Los hermanos McDonald servían en 30 segundos|30 segundos|',
    'H|FRANQUICIAS|Kroc vio el negocio||', 'Y|1961|1954|Kroc|compra la empresa', 'N|2.7|$| M|Pagó|a los hermanos', 'T|Los hermanos se quedaron con su local original|su local|',
    "T|Kroc abrió un McDonald's justo enfrente|enfrente|", 'T|El negocio real eran los terrenos|los terrenos|', 'E|El producto es la hamburguesa. El negocio, el sistema.|el sistema.|¿quién fundó mcdonald\'s?']],
  ['KFC', '#A3080C', '#FFB81C', 'chicken', 'up', ['N|62||años|El coronel Sanders empezó a franquiciar a los|', 'T|Una autopista nueva mató su restaurante|autopista|', 'N|105|$| USD|Vivía de un cheque de retiro de|',
    'H|LA RECETA|11 hierbas y especias||', 'T|Viajaba en auto ofreciendo su receta|en auto|', 'T|Cobraba por cada pollo vendido|por cada pollo|', 'Y|1964|1952|Sanders|vende la empresa',
    'N|2|$| M|Por|', 'T|Nunca es tarde para empezar|tarde|', 'E|Tu edad no es tu excusa.|excusa.|¿a qué edad empezó kfc?']],
  ['Tesla', '#E31937', '#171A20', 'car', 'up', ['Y|2008|2003|Tesla|al borde de la quiebra', 'T|Elon Musk metió su último dinero|su último dinero|', 'T|Ese mismo año fallaban los cohetes de SpaceX|SpaceX|',
    'H|24 DE DICIEMBRE|se cierra la inversión que la salvó||', 'T|Se salvó en Nochebuena|Nochebuena|', 'Y|2012|2008|Model S|sale a la venta', 'T|Model 3: el "infierno de producción"|infierno|',
    'T|Musk dormía en la fábrica|en la fábrica|', 'C|2008 vs. 2020|2008|Casi quiebra|2020|La automotriz más valiosa', 'E|Aguanta un día más que los demás.|un día más|¿tesla casi quiebra?']],
  ['SpaceX', '#005288', '#A7A9AC', 'rocket', 'up', ['Y|2006|2002|SpaceX|primer lanzamiento', 'T|Explotó|Explotó|', 'Y|2007|2006|Intento 2|también falla',
    'H-|3 DE 3|lanzamientos fallidos (2008)||', 'T|Quedaba dinero para un solo intento más|un solo intento|', 'Y|2008|2008|Intento 4|¡llega a órbita!', 'T|Meses después, la NASA les dio un contrato|NASA|',
    'N|1.6|$| mil M|Contrato de|', 'T|Hoy sus cohetes aterrizan solos|aterrizan|', 'E|El cuarto intento es el que cuenta.|cuarto intento|¿spacex falló?']],
  ['Nvidia', '#76B900', '#1A1A1A', 'chip', 'up', ['Y|1993|1990|Nvidia|nace en un Denny\'s', 'T|Su primer chip fue un fracaso|fracaso|', 'Q|Estábamos a 30 días de quebrar.|30 días|Jensen Huang',
    'H|RIVA 128|el chip que los salvó|1997|1993', 'T|Los videojuegos pagaron la investigación|videojuegos|', 'Y|2006|1997|CUDA|las GPU aprenden a hacer de todo', 'T|Esa apuesta hoy entrena a la inteligencia artificial|inteligencia artificial|',
    'N|1|$| billón|En 2023 superó|de valor', 'C|De… a…|1996|30 días de vida|Hoy|El motor de la IA', 'E|Apuesta antes de que sea obvio.|antes|¿cómo empezó nvidia?']],
  ['Zoom', '#2D8CFF', '#0B5CFF', 'laptop', 'up', ['N|8||veces|A Eric Yuan le negaron la visa|', 'T|Llegó a Silicon Valley en 1997|1997|', 'T|Trabajó en WebEx… y no lo escucharon|no lo escucharon|',
    'H|RENUNCIA|para hacer Zoom (2011)||', 'T|Le dijeron que ya había demasiadas apps de video|demasiadas|', 'Y|2020|2011|Pandemia|todos a casa', 'N|300||M|Participantes diarios: de 10 M a|en 4 meses',
    'T|"Hacer Zoom" se volvió verbo|verbo|', 'C|De 10 a 300|Dic 2019|10 M diarios|Abr 2020|300 M diarios', 'E|Que te digan que no, no significa que estés mal.|no significa|¿cómo empezó zoom?']],
  ['WhatsApp', '#25D366', '#075E54', 'chat', 'up', ['Y|2009|2007|Brian Acton|rechazado por Facebook', 'T|También lo rechazó Twitter|Twitter|', 'T|Ese año fundó WhatsApp con Jan Koum|WhatsApp|',
    'H|SIN ANUNCIOS|su regla de oro||', 'Y|2014|2009|Facebook|compra WhatsApp', 'N|19|$| mil M|Facebook pagó|', 'N|55||empleados|WhatsApp tenía|',
    'T|La empresa que no lo contrató le pagó $19,000 M|no lo contrató|', 'C|2009 vs. 2014|2009|"No te contratamos"|2014|$19,000 M', 'E|Un rechazo puede ser tu mejor trato.|mejor trato.|¿facebook rechazó al fundador de whatsapp?']],
  ['Dyson', '#7F00FF', '#C0C0C0', 'vacuum', 'up', ['N|5127||prototipos|James Dyson hizo|', 'T|Su aspiradora perdía fuerza al llenarse|perdía fuerza|', 'T|Se inspiró en el ciclón de un aserradero|ciclón|',
    'H|5 AÑOS|de prototipos||', 'T|Nadie en Europa quiso fabricarla|Nadie|', 'Y|1986|1984|G-Force|se vende en Japón', 'Y|1993|1986|Dyson|abre su propia fábrica',
    'T|Hizo transparente el depósito que otros escondían|transparente|', 'C|El fracaso|Prototipo 1|Fallaba|Prototipo 5,127|Funcionó', 'E|El fracaso es parte del plan.|parte del plan.|¿cuántos prototipos hizo dyson?']],
  ['Spanx', '#E4007C', '#111111', 'tag', 'up', ['N|5000|$| USD|Sara Blakely empezó con|sus ahorros', 'T|Vendía faxes de puerta en puerta|faxes|', 'T|Le cortó los pies a unas medias|cortó los pies|',
    'H-|NO|fábrica tras fábrica||', 'T|Ella misma escribió su patente|patente|', 'T|Una fábrica aceptó porque las hijas del dueño lo entendieron|las hijas|', 'Y|2000|1998|Oprah|la pone entre sus favoritos',
    'T|En 2012 Forbes la nombró multimillonaria|multimillonaria|', 'C|Empezó con|Inversión|$5,000|Resultado|Una marca global', 'E|No esperes permiso.|permiso.|¿cómo empezó spanx?']],
  ['Bimbo', '#0072CE', '#E4002B', 'bread', 'up', ['Y|1945|1940|Bimbo|Ciudad de México', 'T|Sus fundadores eran panaderos|panaderos|', 'T|Pan de caja envuelto en celofán|celofán|',
    'H|EL OSITO|se volvió ícono||', 'T|Su ventaja: la distribución|la distribución|', 'L|Llegó a|Tiendas de la esquina;Escuelas;Carreteras', 'T|Hoy es la panificadora más grande del mundo|más grande del mundo|',
    'N|30||países|Presente en más de|', 'C|De… a…|1945|Ciudad de México|Hoy|30+ países', 'E|Llega a donde está tu cliente.|tu cliente.|¿cómo empezó bimbo?']],
  ['OXXO', '#E4002B', '#FFC72C', 'store', 'up', ['Y|1978|1970|OXXO|Monterrey', 'T|Nació para vender más cerveza|cerveza|', 'T|Una tienda en cada esquina|cada esquina|',
    'H|20,000|tiendas||', 'L|Hoy en OXXO pagas|Luz;Envíos de dinero;Depósitos', 'T|Se volvió el banco del barrio|banco del barrio|', 'T|Abre varias tiendas nuevas cada día|cada día|',
    'N|20000||tiendas|Más de|en Latinoamérica', 'C|Antes y hoy|1978|Vender cerveza|Hoy|Resolver tu día', 'E|Tu canal puede ser tu negocio.|tu negocio.|¿cómo empezó oxxo?']],
  ['Mercado Libre', '#FFE600', '#2D3277', 'box', 'up', ['Y|1999|1995|Mercado Libre|Buenos Aires', 'T|Marcos Galperin escribió el plan en Stanford|Stanford|', 'T|Su primera oficina: un estacionamiento|estacionamiento|',
    'H|EBAY|compra el 19.5% (2001)||', 'T|Creó su propio sistema de pagos|pagos|Mercado Pago', 'T|Construyó su propia red de envíos|envíos|', 'Y|2007|1999|Mercado Libre|sale a bolsa en Nasdaq',
    'T|Hoy es de las empresas más valiosas de Latinoamérica|más valiosas|', 'C|eBay vs. Mercado Libre|eBay|Socio|Mercado Libre|Rey regional', 'E|Resuelve lo local mejor que nadie.|local|¿cómo empezó mercado libre?']],
  ['Volkswagen', '#001E50', '#00B0F0', 'beetle', 'up', ['Y|1938|1930|El Vocho|nace en Alemania', 'N|21.5||M|Se fabricaron más de|unidades', 'T|El auto más vendido con un solo diseño|un solo diseño|',
    'H|PUEBLA|el último vocho||', 'T|El último salió de Puebla, México, en 2003|Puebla|', 'T|Fue el taxi verde de la Ciudad de México|taxi verde|', 'T|Su anuncio "Think small" cambió la publicidad|Think small|',
    'Y|2019|2003|New Beetle|también se despide en Puebla', 'C|Origen y fin|1938|Alemania|2003|Puebla, México', 'E|Pensar en pequeño también vende.|pequeño|¿dónde se hizo el último vocho?']],
  ["Domino's", '#006491', '#E31837', 'pizza', 'up', ["Y|2009|1960|Domino's|las peores reseñas", 'T|Decían que su masa sabía a cartón|cartón|', 'T|La empresa hizo algo rarísimo|rarísimo|',
    'H|"ES MALA"|lo admitieron en TV||', 'T|Cambiaron la receta desde cero|desde cero|', 'T|Pusieron las críticas en sus comerciales|las críticas|', 'T|Después apostaron por pedir desde el celular|celular|',
    'T|Sus acciones se multiplicaron la siguiente década|se multiplicaron|', "C|La jugada|Otros|Esconden la crítica|Domino's|La usa", "E|Admitir el error también vende.|también vende.|¿domino's admitió que su pizza era mala?"]],
  ['Coca-Cola', '#F40009', '#8B0000', 'bottle', 'down', ['Y|1985|1886|Coca-Cola|cambia su fórmula', 'T|Pepsi ganaba las pruebas de sabor|pruebas de sabor|', 'T|La nueva fórmula ganó en pruebas a ciegas|a ciegas|',
    'H|FURIA|de los clientes||', 'N|400000||llamadas|Recibieron más de|y cartas', 'N|79||días|La regresaron en|', 'T|La llamaron "Coca-Cola Classic"|Classic|',
    'T|Y las ventas subieron|subieron|', 'C|El error|Midieron|El sabor|Olvidaron|El cariño', 'E|No vendes un sabor. Vendes un recuerdo.|un recuerdo.|¿qué fue new coke?']],
  ['Hotmail', '#0072C6', '#FF9900', 'mail', 'up', ['Y|1996|1996|Hotmail|correo gratis en la web', 'T|Cada correo llevaba una frase al final|una frase|', 'T|"Obtén tu correo gratis en Hotmail"|gratis|',
    'H|12 M|de usuarios en año y medio||', 'T|Cada usuario invitaba a otro sin saberlo|sin saberlo|', 'Y|1997|1996|Microsoft|compra Hotmail', 'N|400|$| M|Pagó cerca de|',
    'T|El primer gran caso de marketing viral|viral|', 'C|Lo que costó crecer|Anuncios|Millones|Una frase|Gratis', 'E|Haz que tu producto se venda solo.|se venda solo.|¿cómo creció hotmail?']],
  ['Skype', '#00AFF0', '#0078D4', 'laptop', 'down', ['Y|2003|2003|Skype|llamadas gratis por internet', 'N|2.6|$| mil M|eBay la compra por|en 2005', 'N|8.5|$| mil M|Microsoft paga|en 2011',
    'H|TEAMS|Microsoft la reemplaza||', 'T|En la pandemia, todos usaron Zoom|Zoom|', 'T|Skype tenía todo para ganar|todo para ganar|', 'Y|2025|2011|Skype|se apaga en mayo',
    'T|Llegó primero. Se durmió.|Se durmió.|', 'C|2020|Skype|Ya existía|Zoom|Se volvió verbo', 'E|Llegar primero no basta.|no basta.|¿qué pasó con skype?']],
  ['Juicero', '#78BE20', '#FF6B35', 'juicer', 'down', ['N|400|$| USD|Un exprimidor de|conectado a WiFi', 'T|Usaba bolsas de fruta picada|bolsas|', 'N|120|$| M|Recaudó cerca de|',
    'H|A MANO|las bolsas se exprimían igual||', 'T|Un reportaje lo demostró en video|en video|', 'Y|2017|2016|Juicero|cierra', 'T|Resolvía un problema que nadie tenía|nadie tenía|',
    'C|El producto|Máquina|$400|Tus manos|Gratis', 'T|Tecnología sin necesidad es puro gasto|puro gasto|', 'E|Primero el problema, luego el gadget.|el problema|¿qué fue juicero?']],
  ['Fyre Festival', '#F28C28', '#0F9BD7', 'ticket', 'down', ['N|12000|$| USD|Paquetes de hasta|', 'T|Prometía un festival de lujo en una isla|isla|Bahamas', 'T|Lo promovieron modelos e influencers|influencers|',
    'H|CAOS|abril de 2017||', 'T|Tiendas de campaña en vez de villas|campaña|', 'T|El famoso sándwich de queso|sándwich|', 'T|Su fundador fue condenado por fraude|fraude|',
    'T|Un cuadro naranja en Instagram vendió todo|cuadro naranja|', 'C|Lo prometido|Promesa|Lujo en una isla|Realidad|Sándwich de queso', 'E|El marketing no sustituye la operación.|la operación.|¿qué fue fyre festival?']],
  ['Pets.com', '#E4002B', '#00A3E0', 'sock', 'down', ['Y|2000|1998|Pets.com|sale a bolsa', 'T|Vendía comida de mascota por internet|comida de mascota|', 'T|Su mascota era un títere de calcetín|títere|',
    'H|268 DÍAS|después de salir a bolsa, cerró||', 'T|Enviaba bolsas pesadas casi a costo|pesadas|', 'T|Perdía dinero en cada venta|cada venta|', 'T|Gastó millones en un comercial del Super Bowl|Super Bowl|',
    'T|Hoy otras tiendas hacen eso… y funciona|y funciona|', 'C|El problema|Pets.com|Muy temprano|Hoy|Buen momento', 'E|Una buena idea a destiempo es mala idea.|a destiempo|¿qué fue pets.com?']],
  ['Lehman Brothers', '#2D5D8A', '#C9A227', 'building', 'down', ['Y|1850|1844|Lehman Brothers|Montgomery, Alabama', 'N|158||años|Sobrevivió|', 'T|Pasó la Guerra Civil y la Gran Depresión|Gran Depresión|',
    'H|QUIEBRA|15 de septiembre de 2008|2008|1850', 'N|600|$| mil M|Activos por más de|', 'T|La quiebra más grande de la historia de EE.UU.|más grande|', 'T|Apostó todo a hipotecas|hipotecas|',
    'T|Empleados salieron con cajas de cartón|cajas|', 'C|158 años vs. un fin de semana|Historia|158 años|Caída|Días', 'E|Ningún tamaño te hace inmortal.|inmortal.|¿por qué quebró lehman?']],
  ['Enron', '#0057A3', '#C8102E', 'building', 'down', ['N|70|$| mil M|Enron llegó a valer cerca de|', 'T|Fortune la nombró la más innovadora 6 años seguidos|6 años|', 'T|Escondía deudas en empresas fantasma|fantasma|',
    'H|FRAUDE|2001||', 'Y|2001|1985|Enron|se declara en quiebra', 'T|Arrastró a su auditora, Arthur Andersen|Arthur Andersen|', 'N|20000||empleados|Más de|perdieron su trabajo',
    'T|Muchos perdieron también su retiro|su retiro|', 'C|Contabilidad|Lo reportado|Ganancias|La realidad|Deudas', 'E|Si no lo entiendes, pregunta.|pregunta.|¿qué pasó con enron?']],
  ['Hostess', '#0057B8', '#E4002B', 'cake', 'up', ['Y|2012|1930|Hostess|se declara en quiebra', 'T|Adiós a los Twinkies|Twinkies|', 'T|La gente compró Twinkies como si fueran oro|como si fueran oro|',
    'H|REGRESO|2013||', 'T|Nuevos dueños, menos fábricas, más eficiencia|eficiencia|', 'Y|2016|2013|Hostess|vuelve a la bolsa', 'N|5.6|$| mil M|En 2023 la compran por|',
    'T|De la quiebra a valer miles de millones|miles de millones|', 'C|Quiebra vs. regreso|2012|Quiebra|2023|$5,600 M', 'E|Una marca querida vale más que una fábrica.|una marca querida|¿qué pasó con los twinkies?']],
  ['Netflix', '#E50914', '#B20710', 'dvd', 'down', ['Y|2011|2007|Netflix|separa DVD y streaming', 'N|60||%|Subió el precio|', 'T|El DVD se llamaría "Qwikster"|Qwikster|',
    'H|800,000|suscriptores perdidos||', 'N|77||%|Su acción cayó cerca de|', 'T|Reed Hastings pidió disculpas|disculpas|', 'T|Qwikster murió en menos de un mes|menos de un mes|',
    'T|Ni siquiera tenían la cuenta @Qwikster en Twitter|@Qwikster|', 'C|La lección|Netflix|Decidió solo|Clientes|Se fueron', 'E|Explica antes de cambiar.|Explica|¿qué fue qwikster?']],
  ['Gap', '#002868', '#6B8DD6', 'tag', 'down', ['Y|2010|1969|Gap|cambia su logo', 'T|Un logo de 20 años, reemplazado de un día a otro|de un día a otro|', 'T|Nadie había pedido el cambio|pedido|',
    'H|6 DÍAS|duró el nuevo logo||', 'T|Internet lo odió|lo odió|', 'T|Hasta abrieron cuentas burlándose del logo|burlándose|', 'T|Gap regresó al azul de siempre|de siempre|',
    'L|Lo que aprendieron|Escuchar;Probar;No sorprender', 'C|Logo|Viejo|20 años de historia|Nuevo|6 días', 'E|Si funciona, no lo arregles.|no lo arregles.|¿por qué gap quitó su logo?']],
  ['Tropicana', '#F28C00', '#007A33', 'orange', 'down', ['Y|2009|1947|Tropicana|nuevo empaque', 'T|Quitaron la naranja con el popote|el popote|', 'T|La cambiaron por un vaso de jugo|un vaso|',
    'H|−20%|en ventas||', 'N|2||meses|En solo|', 'T|Los clientes no encontraban su jugo|no encontraban|', 'T|Parecía marca genérica|genérica|',
    'T|Regresaron al empaque viejo|viejo|', 'C|Empaque|Viejo|Naranja con popote|Nuevo|Vaso de jugo', 'E|No escondas lo que tus clientes buscan.|buscan.|¿qué pasó con tropicana?']],
  ['Ford', '#003478', '#8FA9C9', 'car', 'down', ['Y|1957|1903|Ford|lanza el Edsel', 'T|Años de estudios de mercado|estudios de mercado|', 'T|Se llamó como el hijo de Henry Ford|el hijo|',
    'H|FRACASO|1959||', 'T|Llegó justo en una recesión|recesión|', 'T|Su parrilla fue blanco de burlas|parrilla|', 'N|250|$| M|Ford perdió cerca de|',
    'T|Su nombre se volvió sinónimo de fracaso|sinónimo|', 'C|Plan vs. mercado|Ford|Estudió años|Clientes|Lo ignoraron', 'E|Escucha al mercado, no a tu ego.|tu ego.|¿qué fue el edsel?']],
  ['Pepsi', '#004B93', '#C9D1D9', 'bottle', 'down', ['Y|1992|1898|Pepsi|lanza Crystal Pepsi', 'T|Refresco de cola… transparente|transparente|', 'T|La moda era lo "puro" y "claro"|claro|',
    'H|CONFUSIÓN|¿sabe a cola o no?||', 'T|No sabía a lo que se veía|lo que se veía|', 'Y|1994|1992|Crystal Pepsi|desaparece', 'T|Hoy es un caso clásico… de error|de error|',
    'T|Volvió por nostalgia en 2016|nostalgia|', 'C|Expectativa|Ojos|Agua|Boca|Refresco', 'E|Que tu producto cumpla lo que promete.|lo que promete.|¿qué fue crystal pepsi?']],
  ['Sony', '#1E3A8A', '#E11D48', 'vhs', 'down', ['Y|1975|1946|Sony|lanza Betamax', 'T|Mejor imagen que la competencia|Mejor imagen|', 'Y|1976|1975|JVC|lanza VHS',
    'H|2 HORAS|grababa VHS||', 'T|Betamax grababa solo una hora al inicio|una hora|', 'T|Una película completa no cabía|no cabía|', 'T|JVC prestó su formato a muchas marcas|muchas marcas|',
    'Y|2002|1976|Sony|deja de fabricar Betamax', 'C|Ganó…|Betamax|Mejor calidad|VHS|Más útil', 'E|Lo mejor no siempre gana. Lo útil sí.|Lo útil sí.|¿por qué perdió betamax?']],
  ['Concorde', '#1F3A93', '#E5E7EB', 'plane', 'down', ['N|3.5||horas|Londres–Nueva York en|', 'T|El doble de rápido que el sonido|doble|', 'N|14||aviones|En servicio solo hubo|',
    'H|2000|el accidente de París||', 'T|Boletos carísimos, pocos asientos|pocos asientos|', 'T|Gastaba muchísimo combustible|combustible|', 'Y|2003|1976|Concorde|último vuelo',
    'T|Nunca tuvo reemplazo|reemplazo|', 'C|Velocidad vs. negocio|Concorde|Más rápido|Jumbo 747|Más rentable', 'E|Rápido no es lo mismo que rentable.|rentable.|¿por qué dejó de volar el concorde?']],
  ['Red Bull', '#DB0A40', '#FFCC00', 'can', 'up', ['Y|1982|1980|Dietrich Mateschitz|viaja a Tailandia', 'T|Probó una bebida para el jet lag|jet lag|', 'T|Se asoció con su creador tailandés|su creador|',
    'H|3 AÑOS|para lanzarla||', 'Y|1987|1984|Red Bull|se lanza en Austria', 'T|No vendía bebida: vendía deportes extremos|deportes extremos|', 'Y|2012|1987|Un salto|desde la estratósfera',
    'T|Es una empresa de medios que vende latas|medios|', 'N|12000||M|En 2023 vendió más de|latas', 'E|Vende la emoción, no el producto.|la emoción|¿cómo empezó red bull?']],
  ['Post-it', '#FFD60A', '#F06292', 'note', 'up', ['Y|1968|1960|3M|un pegamento que no pegaba', 'T|Spencer Silver buscaba un súper pegamento|súper pegamento|', 'T|Le salió uno débil… que se despegaba|débil|',
    'H-|6 AÑOS|sin que nadie le encontrara uso||', 'T|Art Fry necesitaba un separador para su himnario|himnario|', 'T|Que no se cayera… ni rompiera las hojas|ni rompiera|', 'Y|1980|1974|Post-it|llega a las tiendas',
    'T|Regalaron muestras para que la gente lo probara|muestras|', 'C|El error|Buscaban|Pegamento fuerte|Encontraron|Post-it', 'E|Un error puede ser un producto.|un producto.|¿cómo se inventó el post-it?']],
  ['WD-40', '#0057B8', '#FFD100', 'spray', 'up', ['N|40||intentos|Les tomó|', 'T|Buscaban proteger misiles del óxido|misiles|', 'T|WD = "Water Displacement"|Water Displacement|',
    'H|INTENTO 40|funcionó||', 'Y|1958|1953|WD-40|llega a las tiendas', 'T|Los empleados se lo llevaban a escondidas a casa|a escondidas|', 'T|Ahí entendieron el mercado real|mercado real|',
    'T|La fórmula nunca se patentó, para no revelarla|nunca se patentó|', 'C|Para qué era|Plan|Misiles|Realidad|Tu casa', 'E|Persiste hasta el intento 40.|intento 40.|¿qué significa wd-40?']],
  ['Marvel', '#EC1D24', '#1D4ED8', 'comic', 'up', ['Y|1996|1939|Marvel|se declara en quiebra', 'T|Vendió los derechos de sus héroes|derechos|', 'T|Spider-Man a Sony, X-Men a Fox|Sony|',
    'H|PRÉSTAMO|apostó sus personajes (2005)||', 'Y|2008|2005|Iron Man|llega a los cines', 'T|Un héroe "de segunda" salvó a todos|"de segunda"|', 'Y|2009|2008|Disney|compra Marvel',
    'N|4|$| mil M|Disney pagó|', 'T|Avengers: Endgame recaudó casi $2,800 M|$2,800 M|', 'E|Tus activos "menores" pueden salvarte.|salvarte.|¿marvel estuvo en quiebra?']],
  ['Pixar', '#1F6FB2', '#F2C14E', 'lamp', 'up', ['Y|1986|1979|Steve Jobs|compra Pixar a Lucasfilm', 'N|10|$| M|Pagó|', 'T|Pixar vendía computadoras… y no se vendían|no se vendían|',
    'H|TOY STORY|1995||', 'T|La primera película hecha toda por computadora|toda por computadora|', 'T|Jobs puso millones de su bolsillo durante años|de su bolsillo|', 'Y|2006|1995|Disney|compra Pixar',
    'N|7.4|$| mil M|Disney pagó|', 'C|Lo que vendían|1986|Computadoras|1995|Historias', 'E|A veces el demo es el producto.|el producto.|¿cómo empezó pixar?']],
  ['PlayStation', '#003791', '#00AC9F', 'controller', 'up', ['Y|1991|1988|Nintendo y Sony|hacían una consola juntos', 'T|Sony haría un lector de CD para Super Nintendo|lector de CD|', 'T|Sony lo anunció en una feria en 1991|1991|',
    'H-|TRAICIÓN|Nintendo se va con Philips al día siguiente||', 'T|Ken Kutaragi convenció a Sony de seguir solo|seguir solo|', 'Y|1994|1991|PlayStation|sale en Japón', 'N|100||M|La primera PlayStation vendió más de|consolas',
    'T|Nintendo creó a su propio rival|su propio rival|', 'C|Lo que pasó|Nintendo|Rompió el trato|Sony|Creó PlayStation', 'E|Humíllame y me vuelves tu competencia.|competencia.|¿por qué existe playstation?']],
  ['Sega', '#0089CF', '#F26522', 'controller', 'down', ['Y|1999|1960|Sega|lanza Dreamcast', 'T|Tenía internet integrado|internet|', 'T|Adelantada a su tiempo|adelantada|',
    'H|PS2|llegó y se llevó todo||', 'T|Sega venía de varios fracasos|fracasos|', 'Y|2001|1999|Sega|deja de hacer consolas', 'T|Hoy hace juegos para sus antiguos rivales|antiguos rivales|',
    'T|Sonic terminó en consolas de Nintendo|Nintendo|', 'C|2001|Sega|Sin dinero|Sony|Con la PS2', 'E|Llegar antes sin dinero es llegar tarde.|llegar tarde.|¿qué pasó con sega?']],
  ['Groupon', '#53A318', '#82B548', 'ticket', 'down', ['Y|2010|2008|Groupon|cupones del día', 'N|6|$| mil M|Google ofreció|', 'T|Groupon creía valer más|valer más|',
    'H|NO|Groupon rechaza a Google||', 'T|Salió a bolsa en 2011|2011|', 'T|Sus acciones cayeron más de 80% en los años siguientes|80%|', 'T|Copiar cupones era facilísimo|facilísimo|',
    'T|Su fundador fue despedido en 2013|despedido|', 'C|Lo que valía|Oferta de Google|$6,000 M|Años después|Una fracción', 'E|Un descuento no es un modelo de negocio.|modelo de negocio.|¿google quiso comprar groupon?']],
  ['Canva', '#00C4CC', '#7D2AE8', 'palette', 'up', ['N|100||rechazos|Melanie Perkins recibió más de|de inversionistas', 'T|Daba clases de diseño en Perth|Perth|Australia', 'T|Los programas de diseño eran dificilísimos|dificilísimos|',
    'H|SÍ|por fin, un inversionista||', 'Y|2013|2007|Canva|se lanza', 'T|Empezó haciendo anuarios escolares|anuarios|', 'N|40|$| mil M|En 2021 llegó a valer|',
    'T|Diseño fácil para cualquiera|cualquiera|', 'C|Persistencia|Primero|100+ "no"|Después|Gigante del diseño', 'E|Un "no" es solo una opinión.|una opinión.|¿cómo empezó canva?']],
  ['Shopify', '#96BF48', '#5E8E3E', 'snowboard', 'up', ['Y|2004|2000|Snowdevil|tienda online de snowboards', 'T|No encontraron un buen software para vender|software|', 'T|Así que Tobi Lütke lo programó|lo programó|',
    'H|PIVOTE|venden el software, no las tablas||', 'Y|2006|2004|Shopify|se lanza', 'T|Ayuda a cualquiera a abrir su tienda|cualquiera|', 'Y|2015|2006|Shopify|sale a bolsa',
    'T|La herramienta valió más que la tienda|más que la tienda|', 'C|El negocio|Snowboards|Pocos clientes|Software|Millones de tiendas', 'E|Tu herramienta interna puede ser tu producto.|tu producto.|¿cómo empezó shopify?']],
  ['Wrigley', '#C8102E', '#00843D', 'gum', 'up', ['Y|1891|1880|William Wrigley Jr.|Chicago', 'T|Vendía jabón|jabón|', 'T|Regalaba polvo para hornear con cada jabón|polvo para hornear|',
    'H|EL REGALO|gustaba más que el producto||', 'T|Se cambió a vender polvo para hornear|polvo para hornear|', 'T|Y ahora regalaba chicle con el polvo|chicle|', 'Y|1893|1891|Juicy Fruit|sale a la venta',
    'T|El regalo se volvió la empresa|el regalo|', 'C|El negocio|Vendía|Jabón|Terminó vendiendo|Chicle', 'E|Fíjate qué es lo que la gente sí quiere.|sí quiere.|¿cómo empezó wrigley?']],
  ['Avon', '#E4007C', '#7B2D8E', 'perfume', 'up', ['Y|1886|1880|David McConnell|vendía libros puerta por puerta', 'T|Regalaba perfume para que le abrieran|perfume|', 'T|Las clientas preferían el perfume|el perfume|',
    'H|PERFUMES|cambia de negocio||', 'T|Contrató a mujeres para vender|mujeres|', 'T|Les dio ingresos propios antes de que pudieran votar|votar|', 'T|La primera vendedora: Persis Foster Eames Albee|Albee|',
    'L|Su modelo|Venta directa;Catálogo;Comunidad', 'C|De… a…|1886|Libros|Después|Belleza', 'E|Escucha qué regalo funciona mejor.|regalo|¿cómo empezó avon?']],
  ['Swatch', '#E30613', '#00A0E1', 'watch', 'up', ['Y|1969|1960|Seiko|lanza el reloj de cuarzo', 'T|Más preciso y barato que los suizos|barato|', 'T|La relojería suiza se desplomó|desplomó|',
    'H-|2 DE 3|empleos suizos desaparecieron||', 'Y|1983|1969|Swatch|plástico, barato, divertido', 'T|Un reloj suizo como accesorio de moda|moda|', 'T|Mucho más barato que un suizo tradicional|más barato|',
    'T|Con sus ganancias salvaron marcas de lujo|marcas de lujo|', 'C|La respuesta|Japón|Cuarzo barato|Suiza|Cuarzo con estilo', 'E|Si no puedes con ellos, gánales en su juego.|en su juego.|¿cómo se salvó la relojería suiza?']],
  ['Netscape', '#0B5C8E', '#2BB673', 'laptop', 'down', ['N|90||%|Netscape tenía cerca del|de los navegadores', 'Y|1995|1994|Netscape|sale a bolsa', 'T|Su acción se duplicó el primer día|duplicó|',
    'H|GRATIS|Microsoft regala Internet Explorer||', 'T|Venía incluido en Windows|incluido|', 'T|Netscape cobraba a las empresas por su navegador|cobraba|', 'Y|1998|1995|AOL|compra Netscape',
    'T|Su código abierto se volvió Firefox|Firefox|', 'C|Distribución|Netscape|Descargar|Explorer|Ya instalado', 'E|La distribución le gana a la calidad.|distribución|¿qué pasó con netscape?']],
  ['AOL', '#3399FF', '#FFCC00', 'cd', 'down', ['Y|2000|1985|AOL y Time Warner|se fusionan', 'N|165|$| mil M|La fusión valió|', 'T|Internet + medios = el futuro|el futuro|',
    'H|PUNTO COM|la burbuja revienta||', 'T|Llegó el internet de banda ancha|banda ancha|', 'T|Nadie quería conectarse por teléfono|por teléfono|', 'N|99|$| mil M|En 2002 reportaron pérdidas de|',
    'T|Para muchos, la peor fusión de la historia|peor fusión|', 'C|Promesa vs. realidad|2000|$165,000 M|2009|Se separan', 'E|Dos gigantes juntos no hacen un futuro.|un futuro.|¿por qué fracasó aol time warner?']],
  ['Segway', '#E31837', '#6B7280', 'scooter', 'down', ['Y|2001|1999|Segway|"cambiará las ciudades"', 'T|Prometía cambiar cómo nos movemos|cómo nos movemos|', 'N|5000|$| USD|Costaba cerca de|',
    'H|FRACASO|vendió muy poco||', 'T|Pesado, caro y sin lugar dónde usarlo|sin lugar|', 'Y|2015|2001|Ninebot|compra Segway', 'Y|2020|2015|Segway|deja de fabricarse',
    'T|Ganaron los scooters eléctricos baratos|baratos|', 'C|La idea|Segway|$5,000|Scooter|Una fracción', 'E|El precio también es diseño.|diseño.|¿qué pasó con segway?']],
  ['Google Glass', '#4285F4', '#34A853', 'glasses', 'down', ['Y|2013|2012|Google Glass|llega a los primeros usuarios', 'N|1500|$| USD|Costaba|', 'T|Una cámara en tu cara, todo el tiempo|en tu cara|',
    'H|"GLASSHOLES"|así apodaron a sus usuarios||', 'T|La gente se sentía grabada|grabada|', 'T|Bares y cines los prohibieron|prohibieron|', 'Y|2015|2013|Google|deja de venderlo al público',
    'T|Sobrevivió como herramienta de fábrica|de fábrica|', 'C|Para quién|Público|Lo rechazó|Fábricas|Lo usaron', 'E|La tecnología también necesita permiso social.|permiso social.|¿qué pasó con google glass?']],
  ['Ford', '#003478', '#8FA9C9', 'car', 'up', ['Y|1908|1903|Ford|lanza el Modelo T', 'N|12||horas|Armar un auto tomaba|', 'T|Henry Ford copió la idea de los mataderos|mataderos|',
    'H|93 MIN|con la línea de ensamble (1913)||', 'T|Los autos dejaron de ser para ricos|para ricos|', 'N|5|$| al día|Ford pagó a sus obreros|en 1914', 'Q|Del color que quieran, siempre que sea negro.|negro|Henry Ford',
    'N|15||M|Se vendieron más de|Modelos T', 'C|Antes y después|Antes|12 horas|Después|93 minutos', 'E|Hazlo simple. Hazlo para todos.|para todos.|¿cómo cambió ford los autos?']],
  ['Duolingo', '#58CC02', '#1CB0F6', 'book', 'up', ['T|Luis von Ahn creció en Guatemala|Guatemala|', 'T|Coinventó el CAPTCHA|CAPTCHA|', 'Y|2009|2007|Google|compra reCAPTCHA',
    'H|GRATIS|aprender idiomas, para todos||', 'Y|2011|2009|Duolingo|nace en Pittsburgh', 'T|Cada CAPTCHA que escribías ayudaba a digitalizar libros|digitalizar libros|', 'T|Duolingo convirtió aprender en un juego|un juego|',
    'Y|2021|2011|Duolingo|sale a bolsa', 'C|La idea|Escuelas|Caras|Duolingo|Gratis', 'E|Haz que lo difícil se sienta como juego.|como juego.|¿quién creó duolingo?']],
  ['Jarritos', '#F7A400', '#009A44', 'bottle', 'up', ['Y|1950|1940|Jarritos|Ciudad de México', 'T|Primero fue un refresco de café|de café|', 'T|Su nombre viene de los jarritos de barro|de barro|',
    'H|SABORES|de fruta mexicana||', 'T|Sabores mexicanos en vez de copiar a la cola|copiar a la cola|', 'L|Sabores icónicos|Tamarindo;Mandarina;Piña', 'T|Hoy se toma en EE.UU. y en otros países|EE.UU.|',
    'T|La nostalgia mexicana viaja en botella|en botella|', 'C|Estrategia|Otros|Copian la cola|Jarritos|Sabe a México', 'E|Lo local también se exporta.|se exporta.|¿cómo nació jarritos?']],
  ['Topo Chico', '#C8102E', '#F2C14E', 'bottle', 'up', ['Y|1895|1890|Topo Chico|Monterrey', 'T|Agua mineral del Cerro del Topo Chico|Cerro|', 'T|En Texas se volvió de culto|de culto|',
    'H|$220 M|Coca-Cola compra Topo Chico (2017)||', 'T|Su burbuja intensa la hizo famosa|burbuja|', 'T|Los bartenders la volvieron su favorita|bartenders|', 'Y|2020|2017|Topo Chico|lanza hard seltzer',
    'T|De Monterrey a todo EE.UU.|todo EE.UU.|', 'C|Origen y presente|1895|Monterrey|Hoy|Coca-Cola', 'E|Una marca regional puede valer millones.|valer millones.|¿quién compró topo chico?']],
  ['Pepsi', '#004B93', '#E32934', 'bottle', 'up', ['Y|1893|1880|Pepsi|nace como "Brad\'s Drink"', 'T|La inventó otro farmacéutico|farmacéutico|Caleb Bradham', 'T|El azúcar se disparó tras la Primera Guerra Mundial|azúcar|',
    'H-|QUIEBRA|1923||', 'T|Años después, ofrecieron vendérsela a Coca-Cola|vendérsela|', 'T|Coca-Cola dijo que no|no|', 'T|Pepsi vendió el doble por el mismo precio|el doble|',
    'T|Hoy compiten en todo el mundo|todo el mundo|', 'C|El "no"|Coca-Cola|No la compró|Pepsi|Su mayor rival', 'E|Cuidado con a quién le dices que no.|que no.|¿coca-cola pudo comprar pepsi?']],
  ['Listerine', '#0072CE', '#00B2A9', 'bottle', 'up', ['Y|1879|1860|Listerine|antiséptico para cirugías', 'T|Luego se vendió como limpiador de pisos|de pisos|', 'T|Y hasta como remedio para la gonorrea|gonorrea|',
    'H|"HALITOSIS"|el nombre médico del mal aliento||', 'T|Hicieron que la gente se preocupara por su aliento|se preocupara|', 'N|8|$| M|Sus ventas pasaron de $115,000 a|en 7 años', 'T|No cambió el producto. Cambió el problema.|el problema.|',
    'L|Usos de Listerine|Cirugía;Pisos;Aliento', 'C|Antes y después|Antes|Antiséptico|Después|Enjuague bucal', 'E|A veces no cambias el producto, cambias el problema.|cambias el problema.|¿para qué servía listerine?']],
  ['Bubble Wrap', '#00A3E0', '#7DD3FC', 'bubble', 'up', ['Y|1957|1950|Bubble Wrap|nace como papel tapiz', 'T|Papel tapiz con textura de burbujas|papel tapiz|', 'T|No se vendió|No se vendió|',
    'H|IBM|lo usa para empacar computadoras (1960)||', 'T|Antes lo intentaron como aislante de invernaderos|invernaderos|', 'Y|1960|1957|Sealed Air|nace', 'T|Hoy reventarlo es un placer universal|reventarlo|',
    'L|Lo intentaron como|Papel tapiz;Aislante;Empaque', 'C|Plan vs. realidad|Plan|Decorar paredes|Realidad|Proteger envíos', 'E|Tu producto puede servir para algo que no imaginas.|no imaginas.|¿para qué se inventó el plástico de burbujas?']],
  ['Pfizer', '#2E5BFF', '#86A8E7', 'pill', 'up', ['Y|1989|1980|Pfizer|busca un medicamento para el corazón', 'T|Se llamaba sildenafil|sildenafil|', 'T|Para el corazón no funcionó bien|no funcionó|',
    'H|EFECTO SECUNDARIO|que los pacientes no querían devolver||', 'T|Pfizer cambió de enfoque|cambió de enfoque|', 'Y|1998|1989|Viagra|aprobado en EE.UU.', 'T|Uno de los lanzamientos más exitosos de la farmacéutica|más exitosos|',
    'L|Lo que pasó|Fracaso cardiaco;Efecto inesperado;Producto estrella', 'C|El plan|Buscaban|Corazón|Encontraron|Otra cosa', 'E|Observa los efectos secundarios de tu negocio.|efectos secundarios|¿cómo se descubrió el viagra?']],
  ['Colgate', '#E2231A', '#0057B8', 'plate', 'down', ['Y|1982|1806|Colgate|lanza comida congelada', 'T|Sí: comida de la marca de pasta de dientes|pasta de dientes|', 'T|Se llamó "Colgate Kitchen Entrées"|Kitchen Entrées|',
    'H|NADIE|la quiso comprar||', 'T|La marca te hacía pensar en menta|menta|', 'T|¿Lasaña con sabor a dentífrico?|dentífrico|', 'T|Desapareció rapidísimo|rapidísimo|',
    'L|Lo que falló|Marca equivocada;Categoría distinta;Cero sentido', 'C|Asociación|Colgate|Dientes limpios|Comida|Lo que limpias después', 'E|Tu marca tiene límites.|límites.|¿colgate vendió comida?']],
  ['Nutella', '#7B3F00', '#E4002B', 'jar', 'up', ['Y|1946|1940|Pietro Ferrero|Alba, Italia', 'T|El cacao era carísimo después de la guerra|carísimo|', 'T|Lo mezcló con avellanas, que sobraban en la región|avellanas|',
    'H|GIANDUJOT|una barra para cortar con cuchillo||', 'T|Luego la hicieron untable|untable|', 'Y|1964|1951|Nutella|nace', 'T|La escasez creó el producto|escasez|',
    'L|La receta nació de|Escasez;Ingrediente local;Precio bajo', 'C|El problema|Cacao|Caro|Avellana|Abundante', 'E|Crea con lo que tienes.|lo que tienes.|¿cómo nació nutella?']],
];

const num = (s: string) => (s === '' ? undefined : Number(s));
const parse = (s: string, co: string, tone: 'up' | 'down'): Beat => {
  const [k, ...f] = s.split('|');
  switch (k) {
    case 'Y': return { kind: 'year', num: Number(f[0]), from: Number(f[1]), title: f[2], sub: f[3], q: `${f[2]} ${f[0]}`.toLowerCase() };
    case 'N': return { kind: 'num', num: Number(f[0]), pre: f[1] || undefined, suf: f[2] ? (f[2].trim() === '%' ? '%' : ' ' + f[2].trim()) : undefined, title: f[3], sub: f[4] || undefined };
    case 'T': return { kind: 'text', title: f[0], hl: f[1] || undefined, sub: f[2] || undefined };
    case 'Q': return { kind: 'quote', title: `“${f[0]}”`, hl: f[1] || undefined, sub: f[2], who: f[2] };
    case 'M': return { kind: 'chat', title: f[1].split(';').slice(-1)[0], who: f[0], items: f[1].split(';'), hl: f[2] || undefined };
    case 'C': return { kind: 'compare', title: f[0], items: [f[1], f[3]], a: f[2], b: f[4] };
    case 'L': return { kind: 'list', title: f[0], items: f[1].split(';') };
    case 'P': return { kind: 'product', title: f[0], sub: f[1], items: f[2].split(';') };
    case 'H': case 'H-': case 'H+': return { kind: 'crash', title: f[0], sub: f[1], num: num(f[2]), from: num(f[3]), hit: 0.79,
      tone: k === 'H-' ? 'down' : k === 'H+' ? 'up' : tone, q: `${co} ${f[0]}`.toLowerCase().replace(/["“”]/g, '') };
    default: return { kind: 'cta', title: f[0], hl: f[1] || undefined, q: f[2], sub: co };
  }
};
export type Story = { co: string; c1: string; c2: string; prop: string; tone: 'up' | 'down'; beats: Beat[] };
export const STORIES: Story[] = R.map(([co, c1, c2, prop, tone, bs]) => ({ co, c1, c2, prop, tone, beats: bs.map(s => parse(s, co, tone)) }));
// ponytail: a malformed shorthand line only shows up as a broken shot; this guard catches the count at least
if (STORIES.length !== 100 || STORIES.some(s => s.beats.length !== 10)) throw new Error(`stories: ${STORIES.length} / ${STORIES.map((s, i) => s.beats.length !== 10 ? i : '').join('')}`);
